# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls
    cd .. 
    ls

    set -e
    set -x

    cd ..
    ls

    git clone -b beta https://github.com/flutter/flutter.git
    
    export PATH=`pwd`/flutter/bin:$PATH

    echo "Installed flutter to `pwd`/flutter"

    flutter doctor
    echo "Initializing APK Build"
    ls
    flutter build apk --release -v
  displayName: 'install flutter sdk'
